---
title: "Strompreis Vergleich"
author: "Frederik Ziebell"
date: "17 Januar 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- ============================================
Packages
============================================= -->
```{r, echo=FALSE, message=FALSE, warning=FALSE}
library("tidyverse")
library("stringr")
library("glue")
library("cowplot")
```

<!-- ============================================
Data import and processing
============================================= -->
```{r, echo=FALSE, message=FALSE, warning=FALSE}
# import
strom <-read_csv("strom.csv")
gas <-read_csv("gas.csv")

# strompreise berechnen 
strom %<>%
  mutate(tarif=glue("{anbieter}_{tarif}")) %>%
  # preis pro jahr mit 1 jahr vertragslaufzeit
  mutate(preis_1j_1500kwh = (12*preis_mtl_EUR + 1500*preis_pro_kwh_EUR)*(1-erstjahrbonus_prozent/100)-einmal_bonus_EUR,
         preis_1j_1800kwh = (12*preis_mtl_EUR + 1800*preis_pro_kwh_EUR)*(1-erstjahrbonus_prozent/100)-einmal_bonus_EUR,
         preis_1j_2000kwh = (12*preis_mtl_EUR + 2000*preis_pro_kwh_EUR)*(1-erstjahrbonus_prozent/100)-einmal_bonus_EUR
  ) %>%
  # preis pro jahr mit 2 jahre vertragslaufzeit
  mutate(preis_2j_1500kwh = (preis_1j_1500kwh + 12*preis_mtl_EUR + 1500*preis_pro_kwh_EUR)/2,
         preis_2j_1800kwh = (preis_1j_1800kwh + 12*preis_mtl_EUR + 1800*preis_pro_kwh_EUR)/2,
         preis_2j_2000kwh = (preis_1j_2000kwh + 12*preis_mtl_EUR + 2000*preis_pro_kwh_EUR)/2
  ) %>%
  # preis pro jahr mit 3 jahre vertragslaufzeit
  mutate(preis_3j_1500kwh = (2*preis_2j_1500kwh + 12*preis_mtl_EUR + 1500*preis_pro_kwh_EUR)/3,
         preis_3j_1800kwh = (2*preis_2j_1800kwh + 12*preis_mtl_EUR + 1800*preis_pro_kwh_EUR)/3,
         preis_3j_2000kwh = (2*preis_2j_2000kwh + 12*preis_mtl_EUR + 2000*preis_pro_kwh_EUR)/3)

# gaspreise berechnen 
gas %<>%
  mutate(tarif=glue("{anbieter}_{tarif}")) %>%
  # preis pro jahr mit 1 jahr vertragslaufzeit
  mutate(preis_1j_6000kwh = (12*preis_mtl_EUR + 6000*preis_pro_kwh_EUR)*(1-erstjahrbonus_prozent/100)-einmal_bonus_EUR,
         preis_1j_7500kwh = (12*preis_mtl_EUR + 7500*preis_pro_kwh_EUR)*(1-erstjahrbonus_prozent/100)-einmal_bonus_EUR,
         preis_1j_9000kwh = (12*preis_mtl_EUR + 9000*preis_pro_kwh_EUR)*(1-erstjahrbonus_prozent/100)-einmal_bonus_EUR
  ) %>%
  # preis pro jahr mit 2 jahre vertragslaufzeit
  mutate(preis_2j_6000kwh = (preis_1j_6000kwh + 12*preis_mtl_EUR + 6000*preis_pro_kwh_EUR)/2,
         preis_2j_7500kwh = (preis_1j_7500kwh + 12*preis_mtl_EUR + 7500*preis_pro_kwh_EUR)/2,
         preis_2j_9000kwh = (preis_1j_9000kwh + 12*preis_mtl_EUR + 9000*preis_pro_kwh_EUR)/2
  ) %>%
  # preis pro jahr mit 3 jahre vertragslaufzeit
  mutate(preis_3j_6000kwh = (2*preis_2j_6000kwh + 12*preis_mtl_EUR + 6000*preis_pro_kwh_EUR)/3,
         preis_3j_7500kwh = (2*preis_2j_7500kwh + 12*preis_mtl_EUR + 7500*preis_pro_kwh_EUR)/3,
         preis_3j_9000kwh = (2*preis_2j_9000kwh + 12*preis_mtl_EUR + 9000*preis_pro_kwh_EUR)/3)

# tidy strom
strom %<>%
  dplyr::select(anbieter, tarif, 
                preis_1j_1500kwh, preis_1j_1800kwh, preis_1j_2000kwh, 
                preis_2j_1500kwh, preis_2j_1800kwh, preis_2j_2000kwh,
                preis_3j_1500kwh, preis_3j_1800kwh, preis_3j_2000kwh) %>%
  gather(typ, preis, c(preis_1j_1500kwh, preis_1j_1800kwh, preis_1j_2000kwh,
                       preis_2j_1500kwh, preis_2j_1800kwh, preis_2j_2000kwh,
                       preis_3j_1500kwh, preis_3j_1800kwh, preis_3j_2000kwh)
  ) %>%
  mutate(jahr=str_split_fixed(typ,"_",3)[,2],
         verbrauch=str_split_fixed(typ,"_",3)[,3]) %>%
  dplyr::select(-typ)

# tidy gas
gas %<>%
  dplyr::select(anbieter, tarif, 
                preis_1j_6000kwh, preis_1j_7500kwh, preis_1j_9000kwh, 
                preis_2j_6000kwh, preis_2j_7500kwh, preis_2j_9000kwh,
                preis_3j_6000kwh, preis_3j_7500kwh, preis_3j_9000kwh) %>%
  gather(typ, preis, c(preis_1j_6000kwh, preis_1j_7500kwh, preis_1j_9000kwh,
                       preis_2j_6000kwh, preis_2j_7500kwh, preis_2j_9000kwh,
                       preis_3j_6000kwh, preis_3j_7500kwh, preis_3j_9000kwh)
  ) %>%
  mutate(jahr=str_split_fixed(typ,"_",3)[,2],
         verbrauch=str_split_fixed(typ,"_",3)[,3]) %>%
  dplyr::select(-typ)
```

# Strom
# Nur Enstroga
```{r, echo=FALSE, fig.height=5}
strom %>%
  filter(anbieter=="enstroga") %>%
  ggplot(aes(jahr,preis, color=tarif, group=tarif)) +
  facet_grid(~verbrauch) +
  geom_point() +
  geom_line()
```

## Andere Anbieter
```{r, echo=FALSE, fig.width=15, fig.height=15}
strom %>%
  ggplot(aes(jahr,preis, color=tarif, group=tarif)) +
  facet_grid(anbieter~verbrauch) +
  geom_point() +
  geom_line()
```

# Gas
# Nur Enstroga
```{r, echo=FALSE, fig.height=5}
gas %>%
  filter(anbieter=="enstroga") %>%
  ggplot(aes(jahr,preis, color=tarif, group=tarif)) +
  facet_grid(~verbrauch) +
  geom_point() +
  geom_line()
```

## Andere Anbieter
```{r, echo=FALSE, fig.width=15, fig.height=15}
gas %>%
  ggplot(aes(jahr,preis, color=tarif, group=tarif)) +
  facet_grid(anbieter~verbrauch) +
  geom_point() +
  geom_line()
```